name: 'upstrace'
version: '1.0.0'
profile: 'upstrace'

flags:
  send_anonymous_usage_stats: false

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  upstrace:
    staging:
      +materialized: view
    marts:
      +materialized: table